version: "2"
services:
  app:
    container_name: users-api
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    ports:
      - "8080:8080"
    networks:
      - users-network
  mongodb:
    container_name: users_mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - users-network
  datadog:
    build: datadog
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=datadoghq.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    networks:
      - users-nerwork
    ports:
      - "8126:8126/tcp"
networks:
  users-network:
    driver: bridge
